### ISSUE TITLE
centos测试报错import soundfile as sf OSError: sndfile library not found

### ISSUE THREAD

**Issue by qllokirin** [70loKirin/ATRI-plugin#5]
```
[ root @VM-0- 15-centos MoeTTS]# python main.py -tt2ck . /models/atri v2 40000.pt -hgck . /models/g atri hi
figan_ 02510000.pt -hgc . /models/config. json -i私社高性能飞少. -0 output -P basic cleaners
Traceback (most recent call last) :
File "main.py", line
in <module>
from tacotron2 model import Tacotron2
File " / root/ Yunzai Bot/plugins/ATRI -plugin/ resources /MoeTTS/ tacotron2 model.py", line 6，in <module>
from layers import ConvNorm, LinearNorm
Eile " / root/ Yunzai -Bot/plugins/ATRI -plugin/ resources /MoeTTS/ layers.py", line 2，in <module>
from librosa. filters import mel as 1 ibrosa mel fn
File " /usr/local/lib/ python3.7/site-packages/ librosa/_ init .py", line 209，in <module> 
f rom
import core 
File” /usr/ local/ lib/ python3.7/ site-packages/ 1 ibrosa/core/_ init .py", line 6，in <module>
from . audio import
# pyl int: di sable=wi ldcard- import 
File” /usr/ local / lib/ python3.7/ site -packages/ librosa/ core/ audio.py", line 8，in <module>
import soundfile as sf
File " /usr/ local/lib/python3.7/site-packages/ soundfile.py", line 142， in <module>
raise OSError(' sndfile library not found' )
OSError: sndfile library not found
[root@VM-0-15-centos MoeTTS]#
```

**Comment by qllokirin** [comment]
输入`yum install libsndfile`安装缺少的包
可能会遇到yum无法使用的情况 查看#4

**Comment by runmango** [comment]
感谢大佬

**Comment by qllokirin** [comment]
> 感谢大佬

喜欢的话就点个star吧
